### ISSUE TITLE
AX86U华硕官改固件卸载脚本失败

### ISSUE THREAD

**Issue by yuppiesnotzhuhao** [larsonzh/amdwprprsct#59]
/jffs/scripts/lz$ ./uninstall.sh
  2024-06-08 03:35:52

  LZ v4.4.2 uninstall script starts running...
  By LZ (larsonzhang@gmail.com)
  2024-06-08 03:35:52

  LZ script uninstallation failed.
  2024-06-08 03:36:02

**Comment by larsonzh** [comment]
我刚在华硕 GT-AX6000 梅林固件的机器上反复测试了几遍卸载脚本，均可正常执行，相关源代码中也未发现问题，之前也未有人反映类似问题。该脚本代码已很长时间没有更改，用起来十分可靠和稳定。
或许与代码中用到的 read 命令有关，由于手头无相同设备测试，不知代码中的 read 命令格式是否兼容你华硕官改固件里的 Linux 系统。一般意义上，可能性应该不高，因为 read 命令在 Linux 系统中非常通用。但原则上讲，也无法彻底排除情况的发生，毕竟 Linux 版本碎片化现象严重，同一个命令的命令格式可能会有所不同，存在兼容性问题。
正常执行卸载脚本命令时，会出现一条确认卸载是否进行的提示信息： 
Automatically terminate after 10s, continue uninstallation? [Y/N]
键入 Y 或 y 字符则卸载继续执行，其他字符或 10 秒钟未操作，则自动终止执行。
状态如下：
2024-06-08 04:48:38 
LZ v4.4.2 uninstall script starts running... 
By LZ ***@***.***) 
2024-06-08 04:48:38 
Automatically terminate after 10s, continue uninstallation? [Y/N] 
LZ script uninstallation failed. 
2024-06-08 04:48:48 
你给的脚本执行过程中恰恰缺少上面那条提示信息，有些不可思议，不知是如何做到的。
正常的卸载执行过程状态显示如下：
***@***.***:/jffs/scripts/lz# ./uninstall.sh 
2024-06-08 04:03:18 
LZ v4.4.2 uninstall script starts running... 
By LZ ***@***.***) 
2024-06-08 04:03:18 
Automatically terminate after 10s, continue uninstallation? [Y/N] y 
2024-06-08 04:03:28 [769]: 
2024-06-08 04:03:28 [769]: LZ v4.4.2 script commands start...... 
2024-06-08 04:03:28 [769]: By LZ ***@***.***) 
2024-06-08 04:03:28 [769]: --------------------------------------------- 
2024-06-08 04:03:28 [769]: Location: /jffs/scripts/lz 
2024-06-08 04:03:28 [769]: --------------------------------------------- 
2024-06-08 04:03:29 [769]: Policy Routing Web UI has continued to mount. 
2024-06-08 04:03:29 [769]: The service-event interface has continued to register. 
2024-06-08 04:03:29 [769]: Successfully unregistered openvpn-event interface. 
2024-06-08 04:03:29 [769]: Successfully unregistered firewall-start interface. 
2024-06-08 04:03:29 [769]: --------------------------------------------- 
2024-06-08 04:03:29 [769]: Initialization script configuration parameters...... 
2024-06-08 04:03:30 [769]: Configuration parameters initialization is complete. 
2024-06-08 04:03:30 [769]: --------------------------------------------- 
2024-06-08 04:03:30 [769]: Get the router device information...... 
2024-06-08 04:03:30 [769]: --------------------------------------------- 
2024-06-08 04:03:30 [769]: Route Model: GT-AX6000 
2024-06-08 04:03:30 [769]: Hardware Type: aarch64 
......
Uninstallation in progress... 
Software uninstallation completed. 
User data is saved in the original directory. 
2024-06-08 04:03:42 
还有一个带输入参数项强制执行卸载脚本的方式：
./uninstall.sh y
该方式可越过 read 命令的执行段，可以试试。
如果还不能通过 uninstall.sh 命令卸载脚本，可手工方式进行，步骤如下：
直接删除路由器上的 /jffs/scripts/lz 目录；
如果 /jffs/scripts/firewall-start 文件存在，删除文中末尾有 # Added by LZRule 注释的文本命令行；
如果 /jffs/scripts/openvpn-event 文件存在，删除文中末尾有 # Added by LZRule 注释的文本命令行；
如果 /jffs/configs/dnsmasq.conf.add 文件存在，删除该文件；
重启路由器。
上述操作过程执行后，LZ 脚本会被彻底干净且不留痕迹的消灭。
希望上述内容能有所帮助。
LZ
---- 回复的原邮件 ----
***@***.***>发送日期2024年6月8日 ***@***.***>***@***.***>主题[larsonzh/amdwprprsct] AX86U华硕官改固件卸载脚本失败 (Issue #59)
/jffs/scripts/lz$ ./uninstall.sh
2024-06-08 03:35:52
LZ v4.4.2 uninstall script starts running...
By LZ ***@***.***)
2024-06-08 03:35:52
LZ script uninstallation failed.
2024-06-08 03:36:02

**Comment by yuppiesnotzhuhao** [comment]
> 我刚在华硕 GT-AX6000 梅林固件的机器上反复测试了几遍卸载脚本，均可正常执行，相关源代码中也未发现问题，之前也未有人反映类似问题。该脚本代码已很长时间没有更改，用起来十分可靠和稳定。 或许与代码中用到的 read 命令有关，由于手头无相同设备测试，不知代码中的 read 命令格式是否兼容你华硕官改固件里的 Linux 系统。一般意义上，可能性应该不高，因为 read 命令在 Linux 系统中非常通用。但原则上讲，也无法彻底排除情况的发生，毕竟 Linux 版本碎片化现象严重，同一个命令的命令格式可能会有所不同，存在兼容性问题。 正常执行卸载脚本命令时，会出现一条确认卸载是否进行的提示信息：  Automatically terminate after 10s, continue uninstallation? [Y/N] 键入 Y 或 y 字符则卸载继续执行，其他字符或 10 秒钟未操作，则自动终止执行。 状态如下： 2024-06-08 04:48:38 LZ v4.4.2 uninstall script starts running... By LZ ***@***.***) 2024-06-08 04:48:38 Automatically terminate after 10s, continue uninstallation? [Y/N] LZ script uninstallation failed. 2024-06-08 04:48:48 你给的脚本执行过程中恰恰缺少上面那条提示信息，有些不可思议，不知是如何做到的。 正常的卸载执行过程状态显示如下： ***@***.***:/jffs/scripts/lz# ./uninstall.sh 2024-06-08 04:03:18 LZ v4.4.2 uninstall script starts running... By LZ ***@***.***) 2024-06-08 04:03:18 Automatically terminate after 10s, continue uninstallation? [Y/N] y 2024-06-08 04:03:28 [769]: 2024-06-08 04:03:28 [769]: LZ v4.4.2 script commands start...... 2024-06-08 04:03:28 [769]: By LZ ***@***.***) 2024-06-08 04:03:28 [769]: --------------------------------------------- 2024-06-08 04:03:28 [769]: Location: /jffs/scripts/lz 2024-06-08 04:03:28 [769]: --------------------------------------------- 2024-06-08 04:03:29 [769]: Policy Routing Web UI has continued to mount. 2024-06-08 04:03:29 [769]: The service-event interface has continued to register. 2024-06-08 04:03:29 [769]: Successfully unregistered openvpn-event interface. 2024-06-08 04:03:29 [769]: Successfully unregistered firewall-start interface. 2024-06-08 04:03:29 [769]: --------------------------------------------- 2024-06-08 04:03:29 [769]: Initialization script configuration parameters...... 2024-06-08 04:03:30 [769]: Configuration parameters initialization is complete. 2024-06-08 04:03:30 [769]: --------------------------------------------- 2024-06-08 04:03:30 [769]: Get the router device information...... 2024-06-08 04:03:30 [769]: --------------------------------------------- 2024-06-08 04:03:30 [769]: Route Model: GT-AX6000 2024-06-08 04:03:30 [769]: Hardware Type: aarch64 ...... Uninstallation in progress... Software uninstallation completed. User data is saved in the original directory. 2024-06-08 04:03:42 还有一个带输入参数项强制执行卸载脚本的方式： ./uninstall.sh y 该方式可越过 read 命令的执行段，可以试试。 如果还不能通过 uninstall.sh 命令卸载脚本，可手工方式进行，步骤如下： 1.直接删除路由器上的 /jffs/scripts/lz 目录； 2.如果 /jffs/scripts/firewall-start 文件存在，删除文中末尾有 # Added by LZRule 注释的文本命令行； 3.如果 /jffs/scripts/openvpn-event 文件存在，删除文中末尾有 # Added by LZRule 注释的文本命令行； 4.如果 /jffs/configs/dnsmasq.conf.add 文件存在，删除该文件； 5.重启路由器。 上述操作过程执行后，LZ 脚本会被彻底干净且不留痕迹的消灭。 希望上述内容能有所帮助。 LZ ---- 回复的原邮件 ---- ***@***.***>发送日期2024年6月8日 ***@***.***>***@***.***>主题[larsonzh/amdwprprsct] AX86U华硕官改固件卸载脚本失败 (Issue #59) /jffs/scripts/lz$ ./uninstall.sh 2024-06-08 03:35:52 LZ v4.4.2 uninstall script starts running... By LZ ***@***.***) 2024-06-08 03:35:52 LZ script uninstallation failed. 2024-06-08 03:36:02 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

感谢耐心恢复，已经刷了梅林改固件，还在摸索
