### ISSUE TITLE
[两个无伤大雅的小BUG]ax-89x的温度显示不正常，以及误报WAN1断连但实际运行正常

### ISSUE THREAD

**Issue by kingofotaku** [larsonzh/amdwprprsct#68]
日志如下↓
`2024-07-15 03:08:18 [11962]: LZ v4.4.9 script commands start......`
`2024-07-15 03:08:18 [11962]: By LZ (larsonzhang@gmail.com)`
`2024-07-15 03:08:18 [11962]: ---------------------------------------------`
`2024-07-15 03:08:18 [11962]: Location: /jffs/scripts/lz`
`2024-07-15 03:08:18 [11962]: ---------------------------------------------`
`sed: character class syntax is [[:space:]], not [:space:]`
`2024-07-15 03:08:20 [11962]: Successfully registered firewall-start interface.`
`2024-07-15 03:08:20 [11962]: ---------------------------------------------`
`2024-07-15 03:08:20 [11962]: Initialization script configuration parameters......`
`2024-07-15 03:08:21 [11962]: Configuration parameters initialization is complete.`
`2024-07-15 03:08:21 [11962]: ---------------------------------------------`
`2024-07-15 03:08:21 [11962]: Get the router device information......`
`2024-07-15 03:08:22 [11962]: ---------------------------------------------`
`2024-07-15 03:08:22 [11962]:    Route Model: RT-AX89U`
`2024-07-15 03:08:22 [11962]:    Hardware Type: armv7l`
`2024-07-15 03:08:22 [11962]:    Host Name: RT-AX89X-1A78`
`2024-07-15 03:08:22 [11962]:    Kernel Name: Linux`
`2024-07-15 03:08:22 [11962]:    Kernel Release: 4.4.60`
`2024-07-15 03:08:22 [11962]:    Kernel Version: #1 SMP PREEMPT Wed Nov 8 20:26:23 CST 2023`
`2024-07-15 03:08:22 [11962]:    OS Name: GNU/Linux`
`2024-07-15 03:08:22 [11962]:    Firmware Version: 3.0.0.4.388.32407-gb7814fc`
`2024-07-15 03:08:22 [11962]:    Firmware Build: Wed Nov  8 12:25:04 UTC 2023 sadog@5b7ef9b`
`2024-07-15 03:08:22 [11962]:    Repository Site: https://gitee.com/larsonzh/amdwprprsct`
`2024-07-15 03:08:22 [11962]:    CPU temperature: 0.057 degrees C`
`2024-07-15 03:08:22 [11962]:    NVRAM usage: 46399 / 126976 bytes`
`2024-07-15 03:08:22 [11962]:    Route Status: Link`
`2024-07-15 03:08:22 [11962]:    Route Encap: Ethernet`
`2024-07-15 03:08:22 [11962]:    Route HWaddr: 58:11:22:34:1A:7D`
`2024-07-15 03:08:22 [11962]:    Route Local IP Addr: 192.168.1.1`
`2024-07-15 03:08:22 [11962]:    Route Local Bcast: 192.168.1.255`
`2024-07-15 03:08:22 [11962]:    Route Local Mask: 255.255.255.0`
`2024-07-15 03:08:22 [11962]:    Route Usage Mode: Static Policy`
`2024-07-15 03:08:22 [11962]:    Route Policy Mode: Mode 2`
`2024-07-15 03:08:22 [11962]:    Route Domain Policy: Enable`
`2024-07-15 03:08:22 [11962]:    Route Host Access Port: Primary WAN`
`2024-07-15 03:08:22 [11962]:    Proxy Route: Primary WAN`
`2024-07-15 03:08:22 [11962]:    Route Cache Cleaning: Enable`
`2024-07-15 03:08:22 [11962]:    System Caches Cleaning: Enable`
`2024-07-15 03:08:22 [11962]:    Timed Cache Cleaning: Every 24 hours`
`2024-07-15 03:08:22 [11962]: ---------------------------------------------`
`2024-07-15 03:08:22 [11962]: Initializes the policy routing library......`
`2024-07-15 03:08:23 [11962]: ---------------------------------------------`
`2024-07-15 03:08:23 [11962]:    ip_rule_prio_24961 = 2`
`2024-07-15 03:08:23 [11962]:    ip_rule_prio_24963 = 1`
`2024-07-15 03:08:23 [11962]:    ip_rule_prio_24974 = 1`
`2024-07-15 03:08:23 [11962]:    ip_rule_prio_24975 = 1`
`2024-07-15 03:08:23 [11962]:    ip_rule_prio_24978 = 1`
`2024-07-15 03:08:23 [11962]:    ip_rule_prio_24979 = 1`
`2024-07-15 03:08:23 [11962]:    ip_rule_prio_25000 = 1`
`2024-07-15 03:08:23 [11962]: ---------------------------------------------`
`2024-07-15 03:08:23 [11962]: Policy routing library has been initialized.`
`2024-07-15 03:08:24 [11962]: ---------------------------------------------`
`2024-07-15 03:08:24 [11962]:    Update ISP Data: 6:30 Every 3 days`
`2024-07-15 03:08:24 [11962]: ---------------------------------------------`
`2024-07-15 03:08:24 [11962]: Dual WAN ( pppoe -- pppoe ) has been started.`
`2024-07-15 03:08:24 [11962]: The router has successfully joined into two WANs.`
`2024-07-15 03:08:24 [11962]: Policy routing service is being started......`
`2024-07-15 03:09:07 [11962]: ---------------------------------------------`
`2024-07-15 03:09:07 [11962]:    WireGuard Client Detect Time: 5s`
`2024-07-15 03:09:07 [11962]:    Tunnel Address: 10.6.0.1`
`2024-07-15 03:09:07 [11962]:    Listen Port: 51820`
`2024-07-15 03:09:07 [11962]:    WireGuard Client-1: 10.6.0.2`
`2024-07-15 03:09:07 [11962]:    WireGuard Client Export: Primary WAN`
`2024-07-15 03:09:07 [11962]: ---------------------------------------------`
`sed: character class syntax is [[:space:]], not [:space:]`
`2024-07-15 03:09:07 [11962]: Successfully registered openvpn-event interface.`
`2024-07-15 03:09:07 [11962]: ---------------------------------------------`
`2024-07-15 03:09:07 [11962]: Secondary WAN ( eth3 ) fault.`
`2024-07-15 03:09:07 [11962]: Warning: Check and repair immediately.`
`2024-07-15 03:09:07 [11962]: ---------------------------------------------`
`2024-07-15 03:09:07 [11962]:    Primary WAN     Local Area Network`
`2024-07-15 03:09:07 [11962]:                          172.20.247.78`
`2024-07-15 03:09:07 [11962]: ---------------------------------------------`
`2024-07-15 03:09:07 [11962]:    Secondary WAN   Local Area Network`
`2024-07-15 03:09:07 [11962]:                          172.19.29.190`
`2024-07-15 03:09:07 [11962]: ---------------------------------------------`
`2024-07-15 03:09:07 [11962]:    CTCC          * Primary WAN     HD  1728`
`2024-07-15 03:09:07 [11962]:    CUCC/CNC      * Primary WAN     HD  651`
`2024-07-15 03:09:07 [11962]:    CMCC            Primary WAN     HD  49`
`2024-07-15 03:09:07 [11962]:    CRTC            Primary WAN     HD  17`
`2024-07-15 03:09:08 [11962]:    CERNET          Primary WAN     HD  84`
`2024-07-15 03:09:08 [11962]:    GWBN            Primary WAN     HD  173`
`2024-07-15 03:09:08 [11962]:    OTHER           Primary WAN     HD  3311`
`2024-07-15 03:09:08 [11962]:    HONGKONG        Primary WAN     HD  2331`
`2024-07-15 03:09:08 [11962]:    MACAO           Primary WAN     HD  30`
`2024-07-15 03:09:08 [11962]:    TAIWAN          Primary WAN     HD  693`
`2024-07-15 03:09:08 [11962]:    FOREIGN         Primary WAN     HD  -9067`
`2024-07-15 03:09:08 [11962]: ---------------------------------------------`
`2024-07-15 03:09:08 [11962]:    SrcToDstPrt-2   Secondary WAN       1`
`2024-07-15 03:09:08 [11962]:    SrcToDstPrt-1   Primary WAN         1`
`2024-07-15 03:09:08 [11962]:    SrcLst-2        Secondary WAN   HD  1`
`2024-07-15 03:09:08 [11962]:    SrcLst-1        Primary WAN     HD  1`
`2024-07-15 03:09:08 [11962]: ---------------------------------------------`
`2024-07-15 03:09:08 [11962]:    All in High Speed Direct DT Mode.`
`2024-07-15 03:09:08 [11962]: ---------------------------------------------`
`2024-07-15 03:09:09 [11962]: The VPN client route daemon has been started.`
`2024-07-15 03:09:09 [11962]: ---------------------------------------------`
`2024-07-15 03:09:09 [11962]:    ip_rule_prio_24961 = 2`
`2024-07-15 03:09:09 [11962]:    ip_rule_prio_24963 = 1`
`2024-07-15 03:09:09 [11962]:    ip_rule_prio_24974 = 1`
`2024-07-15 03:09:09 [11962]:    ip_rule_prio_24975 = 1`
`2024-07-15 03:09:09 [11962]:    ip_rule_prio_24978 = 1`
`2024-07-15 03:09:09 [11962]:    ip_rule_prio_24979 = 1`
`2024-07-15 03:09:09 [11962]:    ip_rule_prio_25000 = 1`
`2024-07-15 03:09:09 [11962]: ---------------------------------------------`
`2024-07-15 03:09:09 [11962]: Policy routing service has been started successfully.`
`2024-07-15 03:09:09 [11962]: ---------------------------------------------`
`2024-07-15 03:09:09 [11962]: LZ v4.4.9 script commands executed!`
`2024-07-15 03:09:09 [11962]:`
`2024-07-15 03:09:10 [11962]:`
`2024-07-15 03:09:10 [11962]: LZ v4.4.9 Free Memory OK`

**Comment by larsonzh** [comment]
感谢您的细心。

由于是非梅林固件的官改固件设备，固件底层的软件接口及功能与梅林支持的设备存在一些不同，其 CPU 温度数据似乎有 1000 倍差异，已在 v4.5.0 中进行简单修正，请验证一下。关于误报 WAN1 断连，感觉甚为诡异，未查明原因，建议断电重启路由器看看。

**Comment by kingofotaku** [comment]
> 感谢您的细心。
> 
> 由于是非梅林固件的官改固件设备，固件底层的软件接口及功能与梅林支持的设备存在一些不同，其 CPU 温度数据似乎有 1000 倍差异，已在 v4.5.0 中进行简单修正，请验证一下。关于误报 WAN1 断连，感觉甚为诡异，未查明原因，建议断电重启路由器看看。

其实这个bug起码持续有3个版本以上了，因为不影响实际使用，所以也没想着反馈，这次是顺带的。

**Comment by larsonzh** [comment]
> > 感谢您的细心。
> > 由于是非梅林固件的官改固件设备，固件底层的软件接口及功能与梅林支持的设备存在一些不同，其 CPU 温度数据似乎有 1000 倍差异，已在 v4.5.0 中进行简单修正，请验证一下。关于误报 WAN1 断连，感觉甚为诡异，未查明原因，建议断电重启路由器看看。
> 
> 其实这个bug起码持续有3个版本以上了，因为不影响实际使用，所以也没想着反馈，这次是顺带的。

软件基于梅林路由器制作，对非梅林设备的兼容性会存在一些问题，由于差异性多样，也无力去完全兼容这类设备。

**Comment by larsonzh** [comment]
“Secondary WAN ( eth3 ) fault.” 表明系统没有给第二 WAN 口的网卡在系统路由表中正确或无法正确的配置路由。

此时该线路的 pppoe 拨号连接（ppp1）正常，能够上网，但可能无法通过路由器访问该口光猫本地地址。

这种情况在双线路负载均衡情况下快速重启路由器后偶有发生，可能是固件的原因，断电硬重启后有时可恢复正常。

还有一种情况是光猫和路由器本地地址设置不当，或网络中存在设备地址冲突等情况引起，注意不要把这三者的地址设置在同一网段内。可参考如下设置：
-     光猫-1：192.168.1.1
-     光猫-2：192.168.2.1
-     路由器：192.168.50.1

**Comment by kingofotaku** [comment]
> “Secondary WAN ( eth3 ) fault.” 表明系统没有给第二 WAN 口的网卡在系统路由表中正确或无法正确的配置路由。
> 
> 此时该线路的 pppoe 拨号连接（ppp1）正常，能够上网，但可能无法通过路由器访问该口光猫本地地址。
> 
> 这种情况在双线路负载均衡情况下快速重启路由器后偶有发生，可能是固件的原因，断电硬重启后有时可恢复正常。
> 
> 还有一种情况是光猫和路由器本地地址设置不当，或网络中存在设备地址冲突等情况引起，注意不要把这三者的地址设置在同一网段内。可参考如下设置：
> 
> * ```
>   光猫-1：192.168.1.1
>   ```
> * ```
>   光猫-2：192.168.2.1
>   ```
> * ```
>   路由器：192.168.50.1
>   ```

试了下手动指定wan1在光猫下的ip，好像确实有用。
